#ifndef STLINK_VERSION_H_
#define STLINK_VERSION_H_

#define STLINK_VERSION       "1.4.0-14-gfbd55d9"
#define STLINK_VERSION_MAJOR 1
#define STLINK_VERSION_MINOR 4
#define STLINK_VERSION_PATCH 0

#endif /* STLINK_VERSION_ */
